name: Terraform Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init -backend=false

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Validate Syntax
        run: terraform validate -no-color
        
      - name: List Files to be Deployed
        run: |
          echo "## Files that would be deployed:" > deployment-files.md
          echo "" >> deployment-files.md
          echo "### Modules:" >> deployment-files.md
          find modules -type f -name "*.tf" | sort >> deployment-files.md
          echo "" >> deployment-files.md
          echo "### Root Configuration:" >> deployment-files.md
          find . -maxdepth 1 -type f -name "*.tf" | sort >> deployment-files.md
          echo "" >> deployment-files.md
          echo "### Environment-specific Configuration:" >> deployment-files.md
          find environments -type f | sort >> deployment-files.md
          
      - name: Upload Deployment Files List
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: deployment-files.md
          
      - name: ℹ️ Note About Apply
        run: echo "This workflow only validates syntax. To apply changes, you need to run terraform apply locally with proper AWS credentials."